version: '3.8'

services:
  backend:
    container_name: burger-star-backend
    build: ./backend
    restart: always
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/burger/web/staticfiles
      - media_volume:/home/burger/web/media
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    container_name: burger-star-frontend
    build: ./frontend
    depends_on:
      - backend

  db:
    container_name: burger-star-postgres
    image: postgres:14.0-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    build: ./production/nginx
    container_name: burger-star-nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/burger/web/staticfiles
      - media_volume:/home/burger/web/media
    restart: always
    depends_on:
      - web


volumes:
  postgres_volume:
  static_volume:
  media_volume:
