version: '3.8'

services:
  backend:
    container_name: burger-star-backend
    build: ./backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 80:8000
    volumes:
      - static_volume:/home/burger/web/staticfiles
      - media_volume:/home/burger/web/media
      - bundles_volume:/home/burger/web/bundles
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    container_name: burger-star-frontend
    build: ./frontend
    restart: always
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
    ports:
      - 1234:1234
    volumes:
      - bundles_volume:/home/burger/web/bundles
    depends_on:
      - backend

  db:
    container_name: burger-star-postgres
    image: postgres:14.0-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_volume:
  static_volume:
  media_volume:
  bundles_volume:
